CREATE TABLE IF NOT EXISTS Terrains (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Name TEXT NOT NULL,
Letter TEXT NOT NULL,
IsNavegable BOOL NOT NULL,
MovementCost INTEGER NOT NULL,
DefenseModifier INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS Players (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Name TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS Map (
X INTEGER NOT NULL,
Y INTEGER NOT NULL,
TerrainId INTEGER NOT NULL REFERENCES Terrain,
PRIMARY KEY (X, Y));

CREATE TABLE IF NOT EXISTS UnitsTypes (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Name TEXT NOT NULL,
HpMax INTEGER NOT NULL,
Movement INTEGER NOT NULL,
Combat INTEGER NOT NULL,
Sight INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS Units (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Name TEXT NOT NULL,
MovementLeft INTEGER NOT NULL,
Hp INTEGER NOT NULL,
UnitType INTEGER REFERENCES UnitsTypes,
Owner INTEGER REFERENCES Player,
X INTEGER NOT NULL,
Y INTEGER NOT NULL,
FOREIGN KEY (X, Y) REFERENCES Map);

CREATE TABLE IF NOT EXISTS Cities (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Name TEXT NOT NULL,
Owner INTEGER NOT NULL REFERENCES Player,
X INTEGER NOT NULL,
Y INTEGER NOT NULL,
FOREIGN KEY (X, Y) REFERENCES Map);

CREATE TABLE IF NOT EXISTS Buildings (
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Name TEXT NOT NULL,
ProductionModifier INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS BuildingsCities (
CityId INTEGER NOT NULL,
BuildingId INTEGER NOT NULL,
PRIMARY KEY (CityId, BuildingId));
