CREATE TABLE IF NOT EXISTS Productos
(Id INTEGER UNIQUE NOT NULL PRIMARY KEY
,Nombre TEXT NOT NULL
,Cantidad INTEGER NOT NULL
,Precio NUMERIC NOT NULL
,TipoId INTEGER NOT NULL REFERENCES Tipos);

CREATE TABLE IF NOT EXISTS Tipos
(Id INTEGER UNIQUE NOT NULL PRIMARY KEY
,Nombre TEXT NOT NULL);
