CREATE TABLE Pedidos(
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Mesa INTEGER,
Fecha NUMERIC,
Hora NUMERIC);

CREATE TABLE "Pedidos-Productos"(
PedidoID INTEGER NOT NULL REFERENCES Pedidos,
ProductoID INTEGER NOT NULL REFERENCES Productos,
Cantidad INTEGER,
PRIMARY KEY (PedidoID, ProductoID));

CREATE TABLE "Productos"(
Id INTEGER UNIQUE NOT NULL PRIMARY KEY,
Nombre TEXT,
Precio REAL);
